spring.application.name=kihon

# ==========================================
# SUPABASE - POSTGRESQL
# ==========================================

spring.datasource.url=jdbc:postgresql://aws-0-us-east-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.wqlyfrrsmcgksmhfqkpr
spring.datasource.password=Nicole_H14_Flore
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# JPA / HIBERNATE
# ==========================================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# SERVIDOR
# ==========================================

server.port=8080